### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mpash** [mpash/pnpm-next-docker#2]
# Roadmap

## Immediate Goals

- [ ] Support for `pnpm create`
- [ ] Guide for removing standalone builds in favor of standard `next build`s.

## Stretch Goals

- [ ] Support for `[npm|yarn] create`
- [ ] Performance charts between alternatives
